export const CIPHER_SECURITY_LEVELS = {
  LEAD: "SEALED WITH LEAD",
  EQUINOX: "LOCKED UNTIL EQUINOX",
  OCCULT: "DECRYPTION IN PROGRESS",
  IRONBOUND: "IRONBOUND & OCCULT"
};

export const DEFAULT_CIPHER_REWARD_GOLD = 75;
